# Execute with: snakemake ../intermediate_data/[run_name]_sorted.bam ../intermediate_data/run_[run_name] ../data/output/result_[run_name].txt

#rule all:
#    input:
#        "../intermediate_data/{sample}_sorted.bam",
#        "../intermediate_data/run_{sample}",
#        "../intermediate_data/trinity",
#        "../data/output/result.txt"


include: "check_programs"
include: "subsample"
include: "trinity"
include: "busco"
include: "bowtie2"
include: "inferr"
